UPDATE: Python3
SMILE Fixes

TO-DO in smile-master.smile
freekey.py
Line 19: change unichr to chr
################################################################################
ref.py ##########

Python 2.7: implicit hashing
Python 3+: "A class that overrides __eq__() and does not define __hash__() will have its __hash__() implicitly set to None. When the __hash__() method of a class is None, instances of the class will raise an appropriate TypeError when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking isinstance(obj, collections.Hashable)."
	https://docs.python.org/3/reference/datamodel.html#object.__hash
(ref overrides eq but does not define hash, therefore hash was set to None)
	- Running: python video.py
	- Error:
	File "C:\Users\limhe\OneDrive\School\UVa\CompAnalyLab\smile-master\smile - Copy\ref.py", line 223, in add_change_callback
     self.change_callbacks.add((func, pargs, tuple(kwargs.items())))
 	TypeError: unhashable type: 'Ref'

Python 2.7: global function apply()
Python 3+: apply() doesn't exist anymore :(
Line 239: return Ref(apply, self, pargs, kwargs)
Line 37: added an _apply function --> may have to check this again, fix probably isn't the most effective fix

Python 2.7: map() returns list
Python 3+: map() returns iterator
Line 112: map(repr, self.pargs) --> list(map(repr, self.pargs))

################################################################################
state.py ##########

Line 2066 self.__log_filename = none
changed "none" to "None"

Python 2.7: xrange
Python 3+: range

Python 2.7: ---.next()
Python 3+: next(---)
Line 1410 - self.__child_iterator.next()._clone(self))
Line 1442 self.__child_iterator.next()._clone(self))

Python 2.7: __metaclass__ = form
Python 3+: class name(object, metaclass=form)
Line 170 __metaclass__ = StateClass

Python 2.7: xrange
Python 3+: range
*Slight differences in range implementa
tion but shouldn't affect SMILE
Line 463 for distinguisher in xrange(256)

Python 2.7: .__new__(multiple arguments)
Python 3.6: __new__(one argument) (?)
*not sure about this one, need to double check
Line 181 return super(State, cls).__new__(cls, *pargs, **kwargs)

################################################################################
video.py ##########

Line 3111: added kivy.uix.image.Image.__bases__ = (kivy.uix.widget.Widget, BlackHole,)
	- Python 2.7: Passing *args and **kwargs as arguments in super(Class, self).__init__(**kwargs) --> technically not allowed, raises a deprecated warning (to see this, use python -Wdefault file.py)
	- Python 3+: turned the warning into an error
	- BlackHole class just takes up any excess arguments that the base class doesn't have

Python 2.7: '/' worked as integer division (returns an int)
Python 3+: '/' works as true division (returns a float)
Line 3528: exp.screen.width / 4, exp.screen.height / 8
	changed to "//", '/' in python2 is the equivalent to '//' in python3

Python 2.7: dict.keys() returns the keys
Python 3+: dict.keys() returns a dictionary view: dict_keys[(keys)]
Line 341 self._constructor_param_names = param.keys() --> list(param) returns keys
Line 720 pos_prope = (xy_pos_props.keys() + ...)

################################################################################
main.py ##########

Line 369 glVertexAttriPointer(0,2, GL_INT, GL_FALSE, 0, "\x00\x00\x00\x0a\x00\x00\x00\x0a")
Received error: File "C:\Users\limhe\OneDrive\School\UVa\CompAnalyLab\smile-master\smile - Copy\main.py", line 136, in _on_start
     self.do_flip(block=True)
   File "C:\Users\limhe\OneDrive\School\UVa\CompAnalyLab\smile-master\smile - Copy\main.py", line 370, in do_flip
     "\x00\x00\x00\x0a\x00\x00\x00\x0a")
   File "kivy\graphics\opengl.pyx", line 1545, in kivy.graphics.opengl.glVertexAttribPointer (kivy\graphics\opengl.c:19612)
 TypeError: Argument 'data' has incorrect type (expected bytes or int).

################################################################################
 StartScreen_2.py ##########

 removed the **kwargs argument from __init__

 moving_dots.py
 removed **kwargs in super(type(self), self).__init__(**kwargs) in class _MovingDotsWidget(Widget)

changed xrange to range
	- starting dots are different
	- able to run the program
	- dots disappears and exits after pressing 'shift' key

################################################################################
experiment files: ##########

	- no parameters needed under __init__ super
		def __init__(self, **kwargs):
			super(type(self), self).__init__(**kwargs)
		change to:
		def __init__(self, **kwargs):
			super(type(self), self).__init__()
	- xrange -> range
	- .next() -> next()
	- dict.keys() -> list(dict)
	- print statements
	- Add:
		class BlackHole(object):
   		 def __init__(self, **kwargs):
        	super(BlackHole, self).__init__()
     	--> change class Name(Widget): to class Name(Widget, Blackhole)

reinstateMain.py
	- Line 43: / to //
	- Line 68: / to //
	- Line 1: smile.common to common
		- Importing files slightly changed

Common Errors:
	- TypeError: unsupported operand type(s) for /: 'Ref' and 'int'
		- Likely trying to do division --> change / to //

################################################################################
https://stackoverflow.com/questions/4015417/python-class-inherits-object
	- classic style vs new style
	- python 2 vs python 3
https://stackoverflow.com/questions/38397610/how-to-change-the-base-class-in-python
https://docs.python.org/3.0/whatsnew/3.0.html
https://github.com/kivy/kivy/issues/5663
	- BlackHole Fix
https://stackoverflow.com/questions/395982/metaclass-new-cls-and-super-what-is-the-mechanism-exactly
	- super comprehensive explanation
https://stackoverflow.com/questions/19277399/why-does-object-new-work-differently-in-these-three-cases
	- "__init__() complains about excess arguments unless __new__() is overridden and __init__() is not overridden (IOW, if __init__() is overridden or __new__() is not overridden); symmetrically, __new__() complains about excess arguments unless  __init__() is overridden and __new__() is not overridden (IOW, if __new__() is overridden or __init__() is not overridden)."
	- "However, for backwards compatibility, this breaks too much code. Therefore, in 2.6, we'll warn about excess arguments when both methods are overridden; for all other cases we'll use the above rules."
https://stackoverflow.com/questions/100003/what-are-metaclasses-in-python

################################################################################

video.py error --> line 3558: button=Button(text="Click to continue", size=(exp.screen.width//4, exp.screen.height//8))

################################################################################

enter!!
exit!!
enter!!
exit!!
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 22.20.16.4811'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 520'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 22.20.16.4811'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Shader      ] fragment shader: <b"WARNING: 0:4: '' :  #version directive missing">
[INFO   ] [Shader      ] vertex shader: <b"WARNING: 0:4: '' :  #version directive missing">
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
enter!
[INFO   ] [GL          ] NPOT texture support is available
callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
button callback!
leave!!
DEBUG (file: 'Turn on Debug Mode for this information', line: 0) - lag=0.012729s
  label_disappear_time: {'time': 9.944227419337635, 'error': 0.0}
[INFO   ] [Base        ] Leaving application in progress...

Button clicking adds [None] to pressed_list in button_callback